name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      FC: gfortran-9
      CC: gcc-9

    steps:

    - name: install
      run: |
        sudo apt-get install libmpich-dev libnetcdf libnetcdff

    - name: checkout-bacio
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-bacio
        path: bacio
        ref: develop

    - name: build-bacio
      run: |
        cd bacio
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/bacio
        make -j2
        make install

    - name: checkout-w3nco
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-w3nco
        path: w3nco
        ref: develop

    - name: build-w3nco
      run: |
        cd w3nco
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/w3nco
        make -j2
        make install

    - name: checkout
      uses: actions/checkout@v2
      with: 
        path: nemsio
        submodules: true

    - name: build
      run: |
        cd nemsio
        mkdir build 
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/nemsio
        make -j2
        make install
    
